import type { NextPage } from "next"
import Head from "next/head"
import styles from "styles/Home.module.scss"
import Editor from "components/Editor"
import Titlebar from "components/Titlebar"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Groombridge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Titlebar />
      </nav>

      <main className={styles.main}>
        <Editor />
      </main>

      <footer className={styles.footer}>
        <a href="https://valwal.com">By valwal.com</a>
      </footer>
    </div>
  )
}

export default Home
